### PR TITLE
Github Actions CI and pyproject.toml

### PR DESCRIPTION
**Pull request by odrling**
Related: https://github.com/DakaraProject/dakara-feeder/pull/28, https://github.com/DakaraProject/dakara-base/pull/45

This PR adds a Github Actions workflow to dakara-player, and a pyproject.toml file.

I have added a direct dependency to path to the package because it seems to be used in the repository and I don't think we should rely on a deep dependency even if it comes from dakara-base (it can be removed/replaced independently).

Ruff will replace flake8 in a separate PR later.

ubuntu-latest/ubuntu-22.04 segfaults when running the vlc tests, so the workflow is set up to use ubuntu-22.04 instead.

macos-latest is not enabled in the Github Actions workflow but everything is in place to run it once proper macOS support is added to the project. EDIT: maybe not https://github.com/actions/setup-python/issues/314

### CODE REVIEW

**Comment by odrling** [comment]
The mpv package was updated on Chocolatey so the integration tests will fail on windows until #115

**Comment by odrling** [comment]
I think this is what has to be done for codecov after the unit tests/integration tests jobs split
https://about.codecov.io/blog/uploading-code-coverage-in-a-separate-job-on-github-actions/

**Comment by Neraste** [comment]
We have a problem with the latest Mpv version, 0.37.0, on Windows: the official build available on Chocolatey does not give a valid version number, but just a commit hash, `1c9c2f5` (see [this experimental repository](https://github.com/Neraste/test-vlc-mpv-ci/actions/runs/7403259415/job/20142719928)). This makes the code crash at the very beginning of the execution. I'm not sure of the appropriated approach:

- Consider this commit hash `1c9c2f5` as 0.37.0 in the source code: I dont like the idea that the project has to cope with the mistakes of one dude who misspackaged a release;
- Blacklist version 0.37.0 completly on Windows: I don't like the idea that the project will still crash on a specific release of Mpv without any warning message (unlike for VLC blacklisted versions). For the CI, Chocolatey does not allow that, but we can force install a specific version instead (implemented in 2e057aff3dfa0cabc36cde45d0e70ff41cf09e48), but we will have to lift this version limitation in the future. Also, this problem can always happen again later;
- Allow the project to run even if the Mpv version cannot be parsed (and add a warning message on the readme about version 0.37.0 on Windows). This is possible as we can enforce the Mpv version to the code with the config key `player.mpv.force_version` or the environment variable `DAKARA_PLAYER_MPV_FORCE_VERSION`. This was already implemented (but improved in f27ba4d13d63065a6297561e680e0f42b55f157b). On the CI, we can set an environment variable for this, but we will have to lift it in the future.

**Comment by odrling** [comment]
As a preface, from reading bug reports and other conversations around mpv the **"release" builds on Windows are generally not installed by end users**, in part because when installing from the executables found on [Sourceforge](https://sourceforge.net/projects/mpv-player-windows/files/) they are not the first thing that appear. Scoop/Chocolatey do package the release builds however and indeed it breaks when installed this way (but again, it does not seem like a common way to install mpv). **The latest builds** (I tested the 20231231 executable on a Windows computer I found lying around) **do not have this issue and report a correct version number.** So it might not actually be an issue for end users as they might not install the faulty release builds.

Regarding the CI, being able to lock mpv to a particular version for windows seems a bit easier as it means we don't have to change anything else in the workflow, also 0.37.0 would still fail currently, were it built correctly (#115 again).

> Allow the project to run even if the Mpv version cannot be parsed (and add a warning message on the readme about version 0.37.0 on Windows). This is possible as we can enforce the Mpv version to the code with the config key player.mpv.force_version or the environment variable DAKARA_PLAYER_MPV_FORCE_VERSION. This was already implemented (but improved in https://github.com/DakaraProject/dakara-player/commit/f27ba4d13d63065a6297561e680e0f42b55f157b). On the CI, we can set an environment variable for this, but we will have to lift it in the future.

Yes to that, with the exception of the CI bit as I don't think it helps the CI to rely on an env var being set correctly rather than installing a fixed version. **It is testing an uncommon configuration of an user that would install the latest release rather than the first build they found, while it fails ootb on current correctly built builds of mpv** — any build after https://github.com/mpv-player/mpv/commit/df7a094765b58e74a8c1b678d5a8e2374d906866 that did not have the borked version, commit made **months before 0.37.0**, any Windows user with a version installed since August 2023, excluding the week with the borked version number is not being tested and not actually working, **while the CI would test a configuration that we do not want to support** (or at least more than by mentioning that it needs special user configuration to work correctly).
Were it simpler to do I would have tried to install a build from Sourceforge for the CI but I don't think it's worth more effort to install mpv to test that it works on Windows. Testing newer versions of mpv might be easier from a linux distribution, such as alpine that would package versions built from upstream. And the future macOS CI will probably install a (correctly built) 0.37.0 release without issues if testing the latest release available is the goal.

**Comment by Neraste** [comment]
Ideally, we would test different versions of Mpv (at least the most common ones), but this would be a costly process I think (in terms of setup and tests execution time). Indeed, just relying on Chocolatey on Windows CI is *convenient*, but it's not a secret that only devs install applications this way on this OS.

> …when installing from the executables found on [Sourceforge](https://sourceforge.net/projects/mpv-player-windows/files/)…

I don't know what to say when I see [this](https://sourceforge.net/projects/mpv-player-windows/files/64bit/). Mpv may be a good player, but making releases without following semantic versioning is chaotic and hard to handle.

Anyway, if you guarantee that actual installable versions don't suffer from this problem, we can blacklist this specific Chocolatey version on the CI, I guess. It may not be a good idea to use an environment variable to make the tests pass, especially in the light of what you explained. Conversely, we shall create an issue to not forgot to lift the version restriction, and also update the documentation: the force version environment variable/configuration should be used in case of problems with Mpv version detection.

**Comment by odrling** [comment]
> I think this is what has to be done for codecov after the unit tests/integration tests jobs split [about.codecov.io/blog/uploading-code-coverage-in-a-separate-job-on-github-actions](https://about.codecov.io/blog/uploading-code-coverage-in-a-separate-job-on-github-actions/)

Actually it should not *need* this change as all the reports should be uploaded anyway. The coverage just changes "randomly" between commit.

**Comment by odrling** [comment]
I think it should be fine as it is right now. Although I can't explain why some commits ended up with a wildly different code coverage.

**Review by Neraste — APPROVED** [review]
We'll have create an issue for the 2 version locks in the CI (Ubuntu version and mpv version for integration tests).

**Pull request merged**
