### PR TITLE
fix mpv version parsing

### PR DESCRIPTION
**Pull request by odrling**
mpv now reports its version with a 'v' prefixed since this commit: https://github.com/mpv-player/mpv/commit/df7a094765b58e74a8c1b678d5a8e2374d906866

### CODE REVIEW

**Review by Neraste — CHANGES_REQUESTED** [review]
Please add a unit test for the new regex.

**Comment by Neraste** [comment]
Ok, that's great. Please update the docstring of the `get_version` method.

**Comment by odrling** [comment]
OK, I'm a bit bothered by something now.
`get_version` tries to parse post releases from the mpv_version property of mpv and in the format "mpv x.y.z+git.v.w".
This was a bit surprising to me since for as far as I could remember mpv used the [output of `git describe`](https://github.com/mpv-player/mpv/blob/7f1d7c38bcadf982e1bf087327cb445de5e20391/version.sh#L36) for vcs builds which look different.
As it turns out, this version number is only used by the MPV builds of openSUSE, they [patch the source code with their own version string](https://code.opensuse.org/package/mpv/blob/11da4c9c1d2302cb9a5f76a2f588adc0b8dba8d8/f/mpv.spec#_190), so that couldn't work for other platforms/distributions.

Now, that was never a problem with dakara-player since the code never uses anything other than the x.y.z part of the version string. 
So I wonder is there any point in parsing past x.y.z? I don't really expect us to compare versions built from arbitrary vcs tags and if we want to use dakara-player with a new version. Even if mpv changes behaviour between two versions we can still target the next expected version (like 0.38.0 currently) and if the user is unlucky enough to be running one of these builds they could force the mpv version to the next version. (it would be possible to use git to check if a version has a commit that changes the behaviour but that doesn't sound like something that has to be implemented)

**Comment by odrling** [comment]
With the latest commit all post releases should be detected, but the build information from the version string is not kept in any way in the return value. As mentioned in my previous comment dakara-player didn't use this information for anything.

**Comment by Neraste** [comment]
The OpenSUSE specific parsing is mine, since I use this OS. I was facing two problems: mpv usually changes a lot of things between official releases, and those releases are scarce. On OpenSUSE, new packages of mpv are available for the same semver (major.minor.fix), so parsing the post-release indicator was a good thing to distinguish them.

I recognize however that this post-version thingy is not explicitly used in the code. It kinda has a use on the idle screen to indicate that mpv is post-release, but that's all.

Using the timestamp was useful to not simply have `-post0`, but this number doesn't correspond to anything, so simplifying the process is not too bad.

**Comment by odrling** [comment]
Alternatively there could be something to do with the `get_version` command, which returns the version of the C client API (which is somewhat tied to the JSON IPC since it's what it uses)
https://mpv.io/manual/master/#json-ipc-get-version

**Comment by odrling** [comment]
> Alternatively there could be something to do with the `get_version` command, which returns the version of the C client API (which is somewhat tied to the JSON IPC since it's what it uses) [mpv.io/manual/master/#json-ipc-get-version](https://mpv.io/manual/master/#json-ipc-get-version)

That can't seem to help with for example #121

**Comment by Neraste** [comment]
Does it make a difference with how we get the version for now?

**Comment by odrling** [comment]
Well it's just not the same versions, and is more related to the API https://github.com/mpv-player/mpv/blob/master/DOCS/client-api-changes.rst
One obvious issue is that it is not directly updated when commands or properties are changed from what I read. Which doesn't make the changes that broke the player in #121 easier to detect.

**Comment by Neraste** [comment]
If there's no improvement in fetching the API version, then I don't think it's worth to use it.

**Comment by odrling** [comment]
Yes, it doesn't seem particularly better than what we do, and could not reflect changes that we need to know about.
The PR should be fine as it is now.

**Review by Neraste — APPROVED** [review]

**Pull request merged**
